# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20161226_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
